### ISSUE TITLE
Feature suggestion: "Run Code" button like in VS Code

### ISSUE THREAD

**Issue by ArcticDev78** [Zeioth/compiler.nvim#12]
Hi. First of all, thank you for this amazing plugin.
I have one small feature suggestion, would it be somehow possible to add a _"Run Button"_ like the one in **VSCode**?

![Like This](https://code.visualstudio.com/assets/docs/languages/python/run-python-file-in-terminal-button.png)

I am currently using the [AstroNvim](https://github.com/AstroNvim/AstroNvim) Neovim config and I believe it uses [Heirline.nvim](https://github.com/rebelot/heirline.nvim/) for the "Tabs" bar on the top.

PS: I'm still new to Vim/Neovim, so, my apologies if I said anything incorrect above :sweat_smile:

**Comment by Zeioth** [comment]
Hey @ArcticDev78 I'd love that! But I think neovim is not quite there yet. 

The best way to achieve this would probably be a plugin to create a toolbar with icons. Heirline might be a good candidate to implement this in the future. In the meantime, you can open the compiler pressing `F6` by setting the key mappings of the readme section.

Also, consider checking [NormalNvim](https://github.com/NormalNvim/NormalNvim) which is a distro based on astro that come with [Compiler.nvim](https://github.com/Zeioth/compiler.nvim) integration out of the box

![spin](https://github.com/Zeioth/compiler.nvim/assets/3357792/3a959511-b841-47db-8f32-b965be96b963)

In the image you can see a spinner in heirline while compiling. Clicking it will `:ToggleCompilerResults`.
