### ISSUE TITLE
Cmd: Compiler Redo doesn't work

### ISSUE THREAD

**Issue by GustavoPrietoP** [Zeioth/compiler.nvim#13]
```CompilerRedo``` command does not work. This is the error that is shown when i try to run the command: 
![image](https://github.com/Zeioth/compiler.nvim/assets/70907734/ade7940c-bb67-416c-b137-69a90e812fcb)

**Comment by Zeioth** [comment]
Thank you for reporting @GustavoPrietoP that was indeed a regression. I just fixed it and released `v3.0.1`.
