### ISSUE TITLE
Add ts-node as a typescript runner

### ISSUE THREAD

**Issue by benbdb** [Zeioth/compiler.nvim#14]
Add ts-node as an alternative to tsc & node. It's especially useful during development without generating transpiled js files.

**Comment by Zeioth** [comment]
I tested ts-node and it teems this command can fail depending the nodejs version, so we are gonna be keeping tsc+node for now. But with improvements:

* JS files are now generated on ./dist as they were supposed to.
* New compiler options: `npm install`, `npm start`
* All compiler options now require a tsconfig.json file to specify what version of node will be used by tsc (see details in release notes).

## Coming soon
There are plans to integrate makeit.nvim into compiler.nvim in the future. This way users will be able to add not only one, but all their package.json compilation options through a Makefile.

## Coming too (but not soon)
On a second phase, we are gonna implement package.json auto discovery, so all options in the file are automatically listed on compiler.nvim, which is the most desirable scenario.
