### ISSUE TITLE
CompilerToggleResults Bug

### ISSUE THREAD

**Issue by frogiraffe** [Zeioth/compiler.nvim#16]
If i use CompilerOpen and build/run a code, using CompilerToggleResults leaves a empty buffer behind.
![image](https://github.com/Zeioth/compiler.nvim/assets/70097425/12dd8392-7b8e-4ac1-a1fc-fdfbbdf92182)
![image](https://github.com/Zeioth/compiler.nvim/assets/70097425/1a85e7f2-4746-4704-8cba-72d7e8249ca0)

Expected Result: CompilerToggleResults toggling the result window.

**Comment by Zeioth** [comment]
@frogiraffe There has been a change on overseer.nvim

## Short answer
Copy paste [How to install](https://github.com/Zeioth/compiler.nvim#how-to-install) in your config and it should work fine.

## Long answer
That bug happens in the latest version of overseer if you map the key 'q' in the overseer config [as we were doing in previous versions](https://github.com/Zeioth/compiler.nvim/commit/aa6c75ab5dd246b06899a665d21b0f91e6241718)

**Comment by frogiraffe** [comment]
Thank u for the great plugin and for the answer!!

**Comment by frogiraffe** [comment]
Thank u for the great plugin and the answer!!

**Comment by Cliffback** [comment]
I just installed Compiler.nvim, and get the same problem, even with the updated config. What I did was add a command to close empty buffers when toggling CompilerToggleResults, but it is not ideal
