### ISSUE TITLE
Installation directions for vim-plug

### ISSUE THREAD

**Issue by paulusel** [Zeioth/compiler.nvim#21]
I tried installing with vim-plug but it doesn't seem to work. `:CompilerOpen` gives an error. I installed the dependency plugin stevearc/overseer but that didn't help.

**Comment by Zeioth** [comment]
Hello @paulusel [compiler.nvim](https://github.com/Zeioth/compiler.nvim) is a neovim plugin and it is not (currently) available on vim.
