### ISSUE TITLE
Feature Request: expose command for immediately running job

### ISSUE THREAD

**Issue by elu00** [Zeioth/compiler.nvim#24]
Hi,

Thanks for the excellent plugin!
I was wondering if it would be possible to add a command to bypass the language/task type selection and immediately begin compilation, with the resulting language being chosen either by a user-specified priority list or falling back to some internal ranking.

As an example for possible syntax, I'd imagine something like the command `CompilerRun {"cmake", "python", "make"}` first trying to compile the active file with CMake, then falling back to python if the filetype is incorrect, then make, then finally falling back to whatever option is available.

Thanks!

**Comment by Zeioth** [comment]
Sorry for the delay @elu00.

Yes it is possible to execute an action programmatically without need to open Telescope like

```
local language = require("compiler.languages.c")
language.action("option1")
language.action("option2")
language.action("option3")
...etc
```

You have many examples in the [tests directory](https://github.com/Zeioth/compiler.nvim/tree/main/tests/tests) of this repo.
