### ISSUE TITLE
Rust Default output

### ISSUE THREAD

**Issue by jpx40** [Zeioth/compiler.nvim#28]
Hey,
you should update the default output of Rust.

It's the target directory.

Debug build
target/debug

Release build
target/release

**Comment by Zeioth** [comment]
@jpx40 If you use the options `build and run progam`, `build program`, `run program` or `build solution` the output will default to `/bin/program`, as these options use `rustc`. That way you can easily test the compiler without having to create a package.

Now if you want to output to target/debug or target/release you can use cargo by selecting one of the options `cargo build and run`, `cargo build`, `cargo run`, but for these to work, you must create a package, so run `cargo init` on the terminal on your working directory if you didn't already.
