### ISSUE TITLE
zsh : command not found :python

### ISSUE THREAD

**Issue by pjakcs1d** [Zeioth/compiler.nvim#3]
I have used this tip: echo "alias python=/usr/bin/python3" >> ~/.zshrc.
It's avaliable in the terminal.But it can't run by compiler.nvim
![WX20230710-233905@2x](https://github.com/Zeioth/compiler.nvim/assets/90735694/4b381e14-47c7-4b82-94bd-08184548a184)
![WX20230710-233920@2x](https://github.com/Zeioth/compiler.nvim/assets/90735694/5a87742a-dff1-4565-88d4-610401406957)

**Comment by Zeioth** [comment]
That hack shoudn't be necessary. A correct python installation should be available on the system path.

**Comment by Zeioth** [comment]
What's the result of running 

    :term python

Inside nvim? That doesn't look like a bug in compiler.nvim but a shell miss configuration.

**Comment by pjakcs1d** [comment]
<img width="1512" alt="image" src="https://github.com/Zeioth/compiler.nvim/assets/90735694/2ebab852-1332-4dc8-b4d0-c501fba3415e">
I use the command
:term python
The result:
zsh:1: command not found: python

[Process exited 127]

Used The command: :term python3 
It's running



I have used this command 

: echo "alias python=/usr/bin/python3" >> ~/.zshrc.

It's running in the shell,but it's avaliable in the compiler.nvim
<img width="1512" alt="image" src="https://github.com/Zeioth/compiler.nvim/assets/90735694/84eeabea-effc-4e92-9663-9c721eadbd89">
<img width="1487" alt="image" src="https://github.com/Zeioth/compiler.nvim/assets/90735694/2e13c185-4f22-4c78-83ef-bbed9cee7164">

**Comment by pjakcs1d** [comment]
Thanks u so much! 
I install debugpy and use follow command:

export PATH="/Users/luoyaohui/.virtualenvs/debugpy/bin:$PATH"

And ":term python" is running in the nvim-term.

**Comment by Zeioth** [comment]
Glad you have it working fine. Big update coming today/tomorrow with fixes for:

* python build program (mahcine code)
* python build program (bytecode)
* python build program (solution)

**Comment by wookayin** [comment]
alias setting or `$PATH` settings in ~/.zshrc works for an **interactive** shell. `compiler.nvim` or `:term python` will run the program in an non-interactive shell.
