### ISSUE TITLE
run shell file permission denied

### ISSUE THREAD

**Issue by xuliefeng** [Zeioth/compiler.nvim#41]
First of all, thank you so much for an awesome plugin!
Use Run this file to operate on the current shell file, prompting that there are no permissions.

macos 12.7.4

<img width="1728" alt="image" src="https://github.com/Zeioth/compiler.nvim/assets/11550443/4d7d50f6-5fc6-4374-a9ed-234ed3adc0e5">

**Comment by Zeioth** [comment]
Without permissions
![screenshot_2024-05-09_18-08-20_194807216](https://github.com/Zeioth/compiler.nvim/assets/3357792/f14e8987-4625-4ba6-8348-cdf6fa8b122a)

With permissions
![screenshot_2024-05-09_18-08-01_004539025](https://github.com/Zeioth/compiler.nvim/assets/3357792/67e46df6-3ee5-497e-8f8c-781e6454bd4d)
