### ISSUE TITLE
what is this ?

### ISSUE THREAD

**Issue by sachinchaudhary1808** [Zeioth/compiler.nvim#46]
![image](https://github.com/Zeioth/compiler.nvim/assets/138745629/d094e1fa-9640-4feb-ba1f-526fca7cb0d7)

**Comment by Zeioth** [comment]
ld is the linker C uses. so either there is a problem in your code or gcc + binutils is not correctly installed. In which case I recommend you to check: https://github.com/Zeioth/compiler.nvim?tab=readme-ov-file#required-system-dependencies

**Comment by sachinchaudhary1808** [comment]
> `ld` is the linker C uses. so either there is a problem in your code or gcc + binutils is not correctly installed. In which case I recommend you to check: https://github.com/Zeioth/Compiler.nvim/wiki/how-to-install-the-required-dependencies

So the thing ia i use nix aa pkg manager and someone added your pkg to nixpkgs and that's what I'm using

**Comment by Zeioth** [comment]
@sachinchaudhary1808 could you refer me to the package so I can keep an eye on it?

**Comment by sachinchaudhary1808** [comment]
> @sachinchaudhary1808 could you refer me to the package so I can keep an eye on it?

https://search.nixos.org/packages?channel=unstable&show=vimPlugins.compiler-nvim&from=0&size=50&sort=relevance&type=packages&query=compiler+nvim

this is the pkg ( i don't know if u have any idea of nix )

**Comment by sachinchaudhary1808** [comment]
![image](https://github.com/Zeioth/compiler.nvim/assets/138745629/3f33dd7e-41f9-4a5a-ae27-9c547c8a7a58)
