### ISSUE TITLE
Change Compiler

### ISSUE THREAD

**Issue by Fab1anDev** [Zeioth/compiler.nvim#49]
Hi,
Is it possible to change to compiler e.g. gcc -> cc? 
im using FreeBSD and would be very useful.

Regards
Fab1anDev

**Comment by Zeioth** [comment]
Thank you for making me aware of this. What an intelligent convention.

**Comment by Fab1anDev** [comment]
Thank you. It would be nice to have it in [compiler.nvim](https://github/Zeioth/compiler.nvim)

**Comment by Zeioth** [comment]
Actually, @Fab1anDev would be feasible to just create a softlink to gcc? We only support gcc anyway (for clang, you would have to fork the plugin).

**Comment by Zeioth** [comment]
closing in the meantime, but I will read you if you answer.

**Comment by Fab1anDev** [comment]
> closing in the meantime, but I will read you if you answer.

Okay. ill do that. Thanks for the reply :).
