### ISSUE TITLE
feat(event): autocmd

### ISSUE THREAD

**Issue by danielnehrig** [Zeioth/compiler.nvim#5]
Can we have events like

CompilerRunPre
CompilerRunPost

so we can execute logic after compilation has been done or when compiling has been startet
1 use case: for displaying a loading indicator that we are currently building

**Comment by Zeioth** [comment]
@danielnehrig To achieve that, you can [create a custom component](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-components) in your overseer settings.

## Example
In this minimal overseer config, we define the default components that will kick in every time [compiler.nvim](https://github.com/Zeioth/compiler.nvim) start a task.

```lua
{
  "stevearc/overseer.nvim",
  opts = {
    component_aliases = {
      -- Components included in default will apply to all tasks
      default = {
        { "display_duration", detail_level = 2 },
        "on_output_summarize",
        "on_exit_set_status",
        "on_complete_notify",
        "on_complete_dispose",
      },
    },
  },
},
```
From this point, it would be just a matter of creating your own custom component to send your event every time a task is started/finished.

**Comment by Zeioth** [comment]
Overseer has [a bunch of documentation](https://github.com/stevearc/overseer.nvim). It can be quite intimitating. I would start looking into [how components work](https://github.com/stevearc/overseer.nvim/blob/master/doc/explanation.md#components), [list of existing components](https://github.com/stevearc/overseer.nvim/blob/master/doc/components.md) and then read the [third party integration heirline/lualine](https://github.com/stevearc/overseer.nvim#third-party-integrations) before going for [creating your own custom component](https://github.com/stevearc/overseer.nvim/blob/master/doc/guides.md#custom-components), so you have all the info.

**Comment by danielnehrig** [comment]
thanks for the response will look into it

**Comment by danielnehrig** [comment]
@Zeioth thanks for the pointers
overseer is something I've been looking for for quite a while
been searching for a neomake replacement

**Comment by Zeioth** [comment]
@danielnehrig were you are to achieve what you wanted? If so, would you share it? It might be worth adding it to the wiki.

**Comment by danielnehrig** [comment]
![image](https://github.com/Zeioth/compiler.nvim/assets/4050749/56ec0a66-305a-42f3-a95a-68b513d3fe09)
yes i created a component for the statusline to indicate the run process with some fancy animations
@Zeioth

**Comment by Zeioth** [comment]
Thank you for sharing!! I've been able to implementing it too.
![screenshot_2023-07-25_04-36-54_988566464](https://github.com/Zeioth/compiler.nvim/assets/3357792/3790f8e2-c10b-467a-8331-445dc5079fe8)
