### ISSUE TITLE
module 'overseer.register_alias' not found:

### ISSUE THREAD

**Issue by jamesonBradfield** [Zeioth/compiler.nvim#50]
Hello I am trying to get Java Gradle building and run with Compiler, and I am getting this issue,
Here is my minimal config

```lua
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)
require('lazy').setup {
  {
    {
      'Zeioth/compiler.nvim',
      cmd = { 'CompilerOpen', 'CompilerToggleResults', 'CompilerRedo' },
      dependencies = {
        {
          'stevearc/overseer.nvim',
          commit = '6271cab7ccc4ca840faa93f54440ffae3a3918bd',
          cmd = { 'CompilerOpen', 'CompilerToggleResults', 'CompilerRedo' },
          opts = {
            task_list = {
              direction = 'bottom',
              min_height = 25,
              max_height = 25,
              default_detail = 1,
            },
          },
        },
        'nvim-telescope/telescope.nvim',
      },
      opts = {},
    },
    {
      -- Fuzzy Finder (files, lsp, etc)
      'nvim-telescope/telescope.nvim',
      event = 'VimEnter',
      branch = '0.1.x',
      dependencies = {
        'nvim-lua/plenary.nvim',
        'debugloop/telescope-undo.nvim',
      },
    },
  },
}


```

...ocal/share/nvim/lazy/overseer.nvim/lua/overseer/init.lua:578: Error requiring overseer.register_alias: module 'overseer.register_alias' not found:
	no field package.preload['overseer.register_alias']
cache_loader: module overseer.register_alias not found
cache_loader_lib: module overseer.register_alias not found
	no file './overseer/register_alias.lua'
	no file '/home/linuxbrew/.linuxbrew/share/luajit-2.1/overseer/register_alias.lua'
	no file '/usr/local/share/lua/5.1/overseer/register_alias.lua'
	no file '/usr/local/share/lua/5.1/overseer/register_alias/init.lua'
	no file '/home/linuxbrew/.linuxbrew/share/lua/5.1/overseer/register_alias.lua'
	no file '/home/linuxbrew/.linuxbrew/share/lua/5.1/overseer/register_alias/init.lua'
	no file './overseer/register_alias.so'
	no file '/usr/local/lib/lua/5.1/overseer/register_alias.so'
	no file '/home/linuxbrew/.linuxbrew/lib/lua/5.1/overseer/register_alias.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './overseer.so'
	no file '/usr/local/lib/lua/5.1/overseer.so'
	no file '/home/linuxbrew/.linuxbrew/lib/lua/5.1/overseer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /overseer.nvim/lua/overseer/init.lua:578 _in_ **__index**
  - /compiler.nvim/lua/compiler/init.lua:62 _in_ **setup**

**Comment by jamesonBradfield** [comment]
I am running CompilerOpen and getting the above error.

**Comment by Zeioth** [comment]
@jamesonBradfield delete the directory `~/.local/share/nvim/lazy/compiler.nvim`. The latest version requires the overseer `commit = "6271cab7ccc4ca840faa93f54440ffae3a3918bd", which you seem to have, but it seems for some reason it's not installed correctly on your system.

This is the result of running your minimal config on my end (all good).
![screenshot_2024-07-01_11-50-31_402684059](https://github.com/Zeioth/compiler.nvim/assets/3357792/711733f9-b5e5-41e2-831e-3f1a21057118)

**Comment by Zeioth** [comment]
Closing for now. Please let me know if you were not able to solve it.

**Comment by krzychhoo** [comment]
Hey, could we get this issue re-opened as I'm also suffering from the same issue?
```
Failed to run `config` for compiler.nvim
...ocal/share/nvim/lazy/overseer.nvim/lua/overseer/init.lua:578: Error requiring overseer.register_alias: module 'overseer.register_alias' not found:
^Ino field package.preload['overseer.register_alias']
cache_loader: module overseer.register_alias not found
cache_loader_lib: module overseer.register_alias not found
^Ino file './overseer/register_alias.lua'
^Ino file '/usr/share/luajit-2.1/overseer/register_alias.lua'
^Ino file '/usr/local/share/lua/5.1/overseer/register_alias.lua'
^Ino file '/usr/local/share/lua/5.1/overseer/register_alias/init.lua'
^Ino file '/usr/share/lua/5.1/overseer/register_alias.lua'
^Ino file '/usr/share/lua/5.1/overseer/register_alias/init.lua'
^Ino file './overseer/register_alias.so'
^Ino file '/usr/local/lib/lua/5.1/overseer/register_alias.so'
^Ino file '/usr/lib/lua/5.1/overseer/register_alias.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './overseer.so'
^Ino file '/usr/local/lib/lua/5.1/overseer.so'
^Ino file '/usr/lib/lua/5.1/overseer.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /overseer.nvim/lua/overseer/init.lua:578 _in_ **__index**
  - /compiler.nvim/lua/compiler/init.lua:62 _in_ **setup**
 ```
