### ISSUE TITLE
CMake: building target does not work when hypen is part of the executable name

### ISSUE THREAD

**Issue by mjrogozinski** [Zeioth/compiler.nvim#57]
When CMakeLists.txt looks like this, the plugin will attempt to build target `dupa` instead of `dupa-blada`.

```
project(nvim-cpp-gtest)
cmake_minimum_required(VERSION 3.15)
add_executable(dupa-blada main.cpp)
```

The workaround is to replace the hyphen with a different character. An underscore works for me.

**Comment by Zeioth** [comment]
@mjrogozinski should be fixed now.
