### ISSUE TITLE
quick question about build systems

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [Zeioth/compiler.nvim#61]
excuse me if the question is dumb, but I kinda need to know

I noticed that it relies on preexisting build systems (make, cmake, meson, etc), but for some of my projects, they use a custom build script (usually Build.py)

I was wondering if it was possible to configure this plugin to use custom commands for building?

thanks in advance

**Comment by Zeioth** [comment]
@4rtemis-4rrow 

* You create a `Makefile` in your project to run your `.sh` file.
* Compiler.nvim can detect the commands you define inside a `Makefile` and it will list them.
* You can add the `Makefile` to your projec's `.gitignore` so you don't push it by accident.

**Comment by 4rtemis-4rrow** [comment]
that answers my question, tysm m8, and seriously, good job on this plugin
