### ISSUE TITLE
Add optional argument to CompilerOpen

### ISSUE THREAD

**Issue by Groz17** [Zeioth/compiler.nvim#62]
This way you could for example use `CompilerOpen 1` to select the first option without opening Telescope.
This also allows to use `vim.v.count` to dynamically specify an option.

By the way, I found a typo in `lua/compiler/languages/java.lua:8` (progrm -> program)

**Comment by Zeioth** [comment]
You can achieve it this way!

```lua
local language = require('compiler.utils').require_language(vim.bo.filetype)
language.action("option1")
```

**Comment by Zeioth** [comment]
You can achieve it this way!

```lua
local language = require('compiler.utils').require_language(vim.bo.filetype)
language.action("option1")
```

Or in your command line

```lua
:lua require('compiler.utils').require_language(vim.bo.filetype).action("option1")
```

**Comment by Groz17** [comment]
Perfect, thanks for this and the very useful plugin 👍
