### ISSUE TITLE
Options Menu Display Format

### ISSUE THREAD

**Issue by 00y300** [Zeioth/compiler.nvim#63]
I was wondering if there is any way to get the UI to show the input textbox on the top and the options at the bottom. Thanks, for the awesome plugin. 
<img width="617" alt="image" src="https://github.com/user-attachments/assets/d4582c46-dadf-4f60-adfa-7aea3b23f717">

**Comment by Zeioth** [comment]
@00y300 It respects your Telescope  configuration.

Please check into Telescope documentation.

If you have troble with it let me go back to you at the end of the day 😊
