### ISSUE TITLE
 "CompilerOpen" cannot be used.

### ISSUE THREAD

**Issue by ManJack1** [Zeioth/compiler.nvim#9]
I previously upgraded some plugins using lazy.nvim.
And "CompilerOpen" does't work.
When I run this command,It gives me a fllowing error message :
Error:
```lua
Error executing Lua callback: ...share/nvim/lazy/compiler.nvim/lua/compiler/telescope.lua:26: attempt to call field 'requireLanguage' (a nil value)
stack traceback:
	...share/nvim/lazy/compiler.nvim/lua/compiler/telescope.lua:26: in function 'show'
	...ocal/share/nvim/lazy/compiler.nvim/lua/compiler/init.lua:11: in function <...ocal/share/nvim/lazy/compiler.nvim/lua/compiler/init.lua:10>```

**Comment by Zeioth** [comment]
@ManJack1 Please try to add `lazy = false` instead of  `cmd = { "CompilerOpen", "CompilerToggleResults" }` to ensure lazy is loading it correctly.

Also, make sure you are not accidentally locking old versions. I just re-ran all tests and they are passing fine:
![screenshot_2023-08-16_21-12-58_969838478](https://github.com/Zeioth/compiler.nvim/assets/3357792/0e810218-dad7-47a0-bf1a-51100690e8fe)

**Comment by Zeioth** [comment]
Also I see you are defining

```lua
  keys = {
    { "mc", "<cmd>CompilerOpen<cr>", desc = "CompilerOpen" },
    { "mt", "<cmd>CompilerToggleResults<cr>", desc = "CompilerToggleResults" },
  },
```
While I've never used that myself, [I see it's part of lazy](https://github.com/folke/lazy.nvim#-plugin-spec), so double check you are using it correctly.

I might be wrong here, but as I understand, you would use that option like

```
-- Lazy-load on key mapping
keys = {"mc", "mt"}
```

That is not meant to define your keymapping, but to (optionally) say lazy to load the plugin when a key combination is pressed.

You must define keymappings in your keymappings file.

**Comment by ManJack1** [comment]
When I didn't update certain plugins using lazy.nvim (I also don't remember which plugins were updated), the key mapping configurations I set were functional. However, after updating a few plugins, errors started to occur. Interestingly, even when I attempted to use the official configuration, I still couldn't make the "CompilerOpen" work.
![2023-08-17_10-51](https://github.com/Zeioth/compiler.nvim/assets/90735694/ff1833d6-1b15-4b56-89bf-53194255f283)


The error:
```lua
Error executing Lua callback: ...share/nvim/lazy/compiler.nvim/lua/compiler/telescope.lua:26: attempt to call field 'requireLanguage' (a nil value)
stack traceback:
	...share/nvim/lazy/compiler.nvim/lua/compiler/telescope.lua:26: in function 'show'
	...ocal/share/nvim/lazy/compiler.nvim/lua/compiler/init.lua:11: in function <...ocal/share/nvim/lazy/compiler.nvim/lua/compiler/init.lua:10>```

**Comment by Zeioth** [comment]
You are on Windows right @ManJack1? 

[You have to enable WSL](https://www.youtube.com/watch?v=fFbLUEQsRhM). That will allow you to [install the required dependencies as indicated here](https://github.com/Zeioth/Compiler.nvim/wiki/how-to-install-the-required-dependencies). Once you do that you will be able to run [compiler.nvim](https://github.com/Zeioth/compiler.nvim) inside the bash terminal.

![screenshot_2023-08-17_05-26-09_838175687](https://github.com/Zeioth/compiler.nvim/assets/3357792/f3d5b4d1-edc6-4e1b-a2b2-e6ed7b25a05b)

From the FAQ.

**Comment by ManJack1** [comment]
No, my operating system is Arch Linux.

**Comment by Zeioth** [comment]
Now I see where is the issue @ManJack1 thank you for reporting. Update compiler.nvim and you should be able to use it normally now.

**Comment by ManJack1** [comment]
Yes,That's running perfectly now!
Thank you for your kind words of appreciation. I am honored to assist, and I appreciate your recognition of my efforts in providing helpful responses.
